language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
cache: apt
sudo: required
dist: trusty
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1
  - PACKAGE=irmin-watcher
matrix:
  include:
  - env: OCAML_VERSION=4.07
    os: linux
  - env: OCAML_VERSION=4.07 EXTRA_DEPS=inotify
    os: linux
  - env: OCAML_VERSION=4.07 EXTRA_DEPS=osx-fsevents  PINS="osx-cf.dev:https://github.com/mirage/ocaml-osx-cf.git osx-fsevents.dev:https://github.com/mirage/ocaml-osx-fsevents.git"
    os: osx
  - env: OCAML_VERSION=4.06
    os: linux
  - env: OCAML_VERSION=4.05
    os: linux
  - env: OCAML_VERSION=4.04
    os: linux
  - env: OCAML_VERSION=4.03
    os: linux
