language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
cache: apt
sudo: required
dist: trusty
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1
matrix:
  include:
  - env: OCAML_VERSION=4.02
    os: linux
  - env: OCAML_VERSION=4.03
    os: linux
  - env: OCAML_VERSION=4.03 DEPOPTS=osx-fsevents PINS="osx-cf:https://github.com/samoht/ocaml-osx-cf.git#topkg lwt:https://github.com/dsheets/lwt.git#bad-library-search-path-pthread-2.5.2"
    os: osx
    osx_image: xcode7.3
  - env: OCAML_VERSION=4.03 DEPOPTS=inotify
    os: linux
